require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TrackingsController do

  # This should return the minimal set of attributes required to create a valid
  # Tracking. As you add validations to Tracking, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TrackingsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all trackings as @trackings" do
      tracking = Tracking.create! valid_attributes
      get :index, {}, valid_session
      assigns(:trackings).should eq([tracking])
    end
  end

  describe "GET show" do
    it "assigns the requested tracking as @tracking" do
      tracking = Tracking.create! valid_attributes
      get :show, {:id => tracking.to_param}, valid_session
      assigns(:tracking).should eq(tracking)
    end
  end

  describe "GET new" do
    it "assigns a new tracking as @tracking" do
      get :new, {}, valid_session
      assigns(:tracking).should be_a_new(Tracking)
    end
  end

  describe "GET edit" do
    it "assigns the requested tracking as @tracking" do
      tracking = Tracking.create! valid_attributes
      get :edit, {:id => tracking.to_param}, valid_session
      assigns(:tracking).should eq(tracking)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tracking" do
        expect {
          post :create, {:tracking => valid_attributes}, valid_session
        }.to change(Tracking, :count).by(1)
      end

      it "assigns a newly created tracking as @tracking" do
        post :create, {:tracking => valid_attributes}, valid_session
        assigns(:tracking).should be_a(Tracking)
        assigns(:tracking).should be_persisted
      end

      it "redirects to the created tracking" do
        post :create, {:tracking => valid_attributes}, valid_session
        response.should redirect_to(Tracking.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tracking as @tracking" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tracking.any_instance.stub(:save).and_return(false)
        post :create, {:tracking => {}}, valid_session
        assigns(:tracking).should be_a_new(Tracking)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tracking.any_instance.stub(:save).and_return(false)
        post :create, {:tracking => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tracking" do
        tracking = Tracking.create! valid_attributes
        # Assuming there are no other trackings in the database, this
        # specifies that the Tracking created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tracking.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tracking.to_param, :tracking => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tracking as @tracking" do
        tracking = Tracking.create! valid_attributes
        put :update, {:id => tracking.to_param, :tracking => valid_attributes}, valid_session
        assigns(:tracking).should eq(tracking)
      end

      it "redirects to the tracking" do
        tracking = Tracking.create! valid_attributes
        put :update, {:id => tracking.to_param, :tracking => valid_attributes}, valid_session
        response.should redirect_to(tracking)
      end
    end

    describe "with invalid params" do
      it "assigns the tracking as @tracking" do
        tracking = Tracking.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tracking.any_instance.stub(:save).and_return(false)
        put :update, {:id => tracking.to_param, :tracking => {}}, valid_session
        assigns(:tracking).should eq(tracking)
      end

      it "re-renders the 'edit' template" do
        tracking = Tracking.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tracking.any_instance.stub(:save).and_return(false)
        put :update, {:id => tracking.to_param, :tracking => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tracking" do
      tracking = Tracking.create! valid_attributes
      expect {
        delete :destroy, {:id => tracking.to_param}, valid_session
      }.to change(Tracking, :count).by(-1)
    end

    it "redirects to the trackings list" do
      tracking = Tracking.create! valid_attributes
      delete :destroy, {:id => tracking.to_param}, valid_session
      response.should redirect_to(trackings_url)
    end
  end

end
